cmake_minimum_required(VERSION 3.16)

project(tcp_demo VERSION 0.1 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(Qt6 REQUIRED COMPONENTS Core Network)

qt_standard_project_setup()

qt_add_executable(tcp_demo
    main.cpp
    tcpserver.h
    tcpserver.cpp
    tcpclient.h
    tcpclient.cpp
)

target_link_libraries(tcp_demo PRIVATE Qt6::Core Qt6::Network)
